---
title: "IREF_theoryCSFigures_09-29-25"
author: "Andy"
date: "2025-09-29"
output: pdf_document
---

```{r, include = FALSE}
library(ggplot2)
library(cowplot)
library(ggbrace)
library(knitr)
knitr::opts_chunk$set(tidy.opts = list(width.cutoff = 60), tidy = TRUE)
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```


```{r Figure 1: IREF General Example}
baseline.df <- read.csv("1-1_displacement_baseline.csv")
baseline_summary.df <- read.csv("1-4_displacement_summary.csv") # Find a way to read in the optimums from here

fig1_a.plot <- ggplot( data = baseline.df, aes( x = trait ) ) +
  geom_line( aes( y = growth_curve, color = "Growth" ), size = 1 ) +
  geom_line( aes( y = mort_curve, color = "Mortality" ), size = 1, linetype = "dashed" ) +
  theme_classic( base_size = 10, base_line_size = 1 ) + 
  ylab("Growth and Mortality") +
  xlab("Trait Expression") +
  scale_x_continuous(expand = c(0, 0), breaks = c(0, 0.5, 1), labels = c("Low", "", "High") ) + 
  scale_y_continuous(expand = c(0, 0), limits = c(0, 1), breaks = c(0, 0.5, 1) ) +
  annotate( "text", x = 0.25, y = 0.85, label = "Growth", size = 9/.pt  ) +
  annotate( "text", x = 0.5, y = 0.35, label = "Mortality", size = 9/.pt  ) +
  scale_color_manual(name = "Curve", values = c( "blue", "red" )) + 
  theme( panel.border = element_rect( color = "black", fill = NA, linewidth = 0.75 ), aspect.ratio = 1, legend.position = "bottom", plot.margin = margin(10, 15, 10, 10)) + 
  theme(legend.key = element_rect(fill = "white"), legend.text = element_text(color = "white"), legend.title = element_text(color = "white")) +
  guides(color = guide_legend(override.aes = list(color = NA)))

fig1_b.plot <- ggplot( data = baseline.df, aes( x = trait ) ) +
  geom_line( aes( y = growth_curve, color = "Growth" ), size = 1 ) +
  geom_line( aes( y = mort_curve, color = "Mortality" ), size = 1, linetype = "dashed" ) +
  geom_ribbon( aes(xmin = 0.01, xmax = 0.99, ymin = growth_curve, ymax = 0.998), 
               color = NA, fill = "lightblue", alpha = 0.5) +
  geom_ribbon( aes(xmin = 0.01, xmax = 0.99, ymin = 0, ymax = mort_curve), 
               color = NA, fill = "red", alpha = 0.5) +
  geom_ribbon( aes(xmin = 0.01, xmax = 0.99, ymin = mort_curve, ymax = growth_curve), 
               color = NA, fill = "lightgreen", alpha = 0.5) +
  theme_classic( base_size = 10, base_line_size = 1 ) + 
  ylab("Growth and Mortality") +
  xlab("Trait Expression") +
  annotate( "text", x = 0.5, y = 0.5, label = "Fitness = 1 - NCE - CE", size = 9/.pt  ) +
  annotate( "text", x = 0.5, y = 0.95, label = "NCE", size = 9/.pt  ) +
  annotate( "text", x = 0.5, y = 0.15, label = "CE", size = 9/.pt  ) +
  scale_x_continuous(expand = c(0, 0), breaks = c(0, 0.5, 1), labels = c("Low", "", "High") ) + 
  scale_y_continuous(expand = c(0, 0), limits = c(0, 1), breaks = c(0, 0.5, 1) ) +
  scale_color_manual(name = "Curve", values = c( "blue", "red" )) + 
  theme( panel.border = element_rect( color = "black", fill = NA, linewidth = 0.75 ), aspect.ratio = 1,
         axis.title.y = element_blank(), legend.position = "bottom",
         plot.margin = margin(10, 15, 10, 10))

fig1_c.plot <- ggplot( data = baseline.df, aes( x = trait ) ) +
  geom_line( aes( y = growth_curve, color = "Growth" ), size = 1 ) +
  geom_line( aes( y = mort_curve, color = "Mortality" ), size = 1, linetype = "dashed" ) +
  theme_classic( base_size = 10, base_line_size = 1 ) + 
  ylab("Growth and Mortality") +
  xlab("Trait Expression") +
  annotate(geom = "rect", xmin = baseline_optim - 0.025, xmax = baseline_optim + 0.025, 
           ymin = 1 - baseline_optim_NCE, ymax = 0.998, 
           color = "gray2", fill = "lightblue", alpha = 0.5) +
  annotate( "text", x = baseline_optim + 0.05, y = 1 - baseline_optim_NCE/2, 
            label = "NCE = 0.12", hjust = "left", size = 9/.pt  ) +
  annotate(geom = "rect", xmin = baseline_optim - 0.025, xmax = baseline_optim + 0.025,
           ymin = baseline_optim_CE, ymax = baseline_optim_CE + baseline_optim_fitness, 
           color = "gray2", fill = "lightgreen", alpha = 0.5) +
  annotate( "text", x = baseline_optim + 0.1, y = baseline_optim_CE + baseline_optim_fitness/2, 
            label = "0.66", hjust = "left", size = 9/.pt  ) +
  annotate(geom = "rect", xmin = baseline_optim - 0.025, xmax = baseline_optim + 0.025, 
           ymin = 0.001, ymax = baseline_optim_CE, 
           color = "gray2", fill = "red", alpha = 0.5) +
  annotate( "text", x = baseline_optim + 0.05, y = baseline_optim_CE/2 - 0.05, 
            label = "CE = 0.22", hjust = "left", size = 9/.pt  ) +
  scale_x_continuous(expand = c(0, 0), breaks = c(0, 0.5, 1), labels = c("Low", "", "High") ) + 
  scale_y_continuous(expand = c(0, 0), limits = c(0, 1), breaks = c(0, 0.5, 1) ) +
  scale_color_manual(name = "Curve", values = c( "blue", "red" )) + 
  theme( panel.border = element_rect( color = "black", fill = NA, linewidth = 0.75 ), aspect.ratio = 1,
         axis.title.y = element_blank(), legend.position = "bottom",
         plot.margin = margin(10, 15, 10, 10) ) + 
  theme(legend.key = element_rect(fill = "white"), legend.text = element_text(color = "white"), legend.title = element_text(color = "white")) +
  guides(color = guide_legend(override.aes = list(color = NA)))


fig1.plot <- plot_grid( fig1_a.plot, fig1_b.plot, fig1_c.plot, ncol = 3, labels = "auto", label_y = 0.75, align = c("hv") )

# ggsave("fig1.png", plot = fig1.plot, dpi = 300)
```


```{r Figure 2: Displacement Rate - Increasing Predator Density}
preddens.df <- read.csv("1-2-1_displacement_preddens.csv")
preddens_pctNCE.df <- read.csv("1-2-2_preddens_TPE_Opt.csv")

# Fig. 2 - predator density
preddens_1.plot <- ggplot( data = baseline.df, aes( x = trait ) ) +
  geom_line( aes( y = growth_curve, color = "Growth" ) ) +
  geom_line( aes( y = mort_curve, color = "Mortality" ), linetype = "dashed" ) +
  annotate(geom = "rect", xmin = baseline_optim - 0.025, xmax = baseline_optim + 0.025, 
           ymin = 1 - baseline_optim_NCE, ymax = 0.998, 
           color = "gray2", fill = "lightblue", alpha = 0.5) +
  annotate( "text", x = baseline_optim + 0.05, y = 1 - baseline_optim_NCE/2, 
            label = "NCE = 0.12", hjust = "left", size = 8/.pt  ) +
  annotate(geom = "rect", xmin = baseline_optim - 0.025, xmax = baseline_optim + 0.025,
           ymin = baseline_optim_CE, ymax = baseline_optim_CE + baseline_optim_fitness, 
           color = "gray2", fill = "lightgreen", alpha = 0.5) +
  annotate( "text", x = baseline_optim + 0.1, y = baseline_optim_CE + baseline_optim_fitness/2, 
            label = "0.66", hjust = "left", size = 8/.pt  ) +
  annotate(geom = "rect", xmin = baseline_optim - 0.025, xmax = baseline_optim + 0.025, 
           ymin = 0.001, ymax = baseline_optim_CE, 
           color = "gray2", fill = "red", alpha = 0.5) +
  annotate( "text", x = baseline_optim + 0.05, y = baseline_optim_CE/2 - 0.05, 
            label = "CE = 0.22", hjust = "left", size = 8/.pt  ) +
  annotate("text", x = 0.125, y = 0.05, label = "P = 0.45", size = 9/.pt ) +
  theme_classic( base_size = 10, base_line_size = 1 ) + 
  ylab("Growth and Mortality") +
  xlab("Displacement Rate") +
  scale_x_continuous(expand = c(0, 0), breaks = c(0, 0.5, 1), labels = c(1000, 500, 1) ) + 
  scale_y_continuous(expand = c(0, 0), limits = c(0, 1), breaks = c(0, 0.5, 1) ) +
  scale_color_manual(name = "Curve", values = c( "blue", "red" )) + 
  theme( panel.border = element_rect( color = "black", fill = NA, linewidth = 0.75 ), aspect.ratio = 1,
         axis.title.x = element_blank(),
         axis.text.x = element_blank(), legend.position = "bottom" ) + 
  theme(legend.key = element_rect(fill = "white"), legend.text = element_text(color = "white"), legend.title = element_text(color = "white")) +
  guides(color = guide_legend(override.aes = list(color = NA)))

preddens_2.plot <- ggplot( data = preddens.df, aes( x = trait ) ) +
  geom_line( aes( y = growth_curve, colour = "Growth" ), ) +
  geom_line( aes( y = mort_curve, colour = "Mortality" ), linetype = "dashed" ) +
  theme_classic( base_size = 10, base_line_size = 1 ) + 
  ylab("Growth and Mortality") +
  xlab("Displacement Rate") +
  annotate(geom = "rect", xmin = preddens_optim - 0.025, xmax = preddens_optim + 0.025, 
           ymin = 1 - preddens_optim_NCE, ymax = 0.998, 
           color = "gray2", fill = "lightblue", alpha = 0.5) +
  annotate( "text", x = preddens_optim + 0.05, y = 1 - preddens_optim_NCE/2, 
            label = "NCE = 0.20", hjust = "left", size = 7/.pt  ) +
  annotate(geom = "rect", xmin = preddens_optim - 0.025, xmax = preddens_optim + 0.025,
           ymin = preddens_optim_CE, ymax = preddens_optim_CE + preddens_optim_fitness, 
           color = "gray2", fill = "lightgreen", alpha = 0.5) +
  annotate( "text", x = preddens_optim + 0.1, y = preddens_optim_CE + preddens_optim_fitness/2 - 0.1, 
            label = "0.48", hjust = "left", size = 7/.pt  ) +
  annotate(geom = "rect", xmin = preddens_optim - 0.025, xmax = preddens_optim + 0.025, 
           ymin = 0.001, ymax = preddens_optim_CE, 
           color = "gray2", fill = "red", alpha = 0.5) +
  annotate( "text", x = preddens_optim + 0.05, y = preddens_optim_CE/2 - 0.05, 
            label = "CE = 0.32", hjust = "left", size = 7/.pt  ) +
  annotate("text", x = 0.125, y = 0.05, label = "P = 0.90", size = 9/.pt ) +
  scale_x_continuous(expand = c(0, 0), breaks = c(0, 0.5, 1), labels = c(1000, 500, 1) ) + 
  scale_y_continuous(expand = c(0, 0), limits = c(0, 1), breaks = c(0, 0.5, 1) ) +
  scale_colour_manual(name = "Curve", values = c("blue", "red")) +
  theme( panel.border = element_rect( color = "black", fill = NA, linewidth = 0.75 ), aspect.ratio = 1 ) +
  theme( legend.position = "bottom" )

preddens_3.plot <- ggplot( data = preddens_pctNCE.df, aes( x = k ) ) +
  geom_point( aes( y = NCE_TPE, fill = Fitness ), color = "black", shape = 21, size = 2.5 ) +
  theme_classic( base_size = 10, base_line_size = 1 ) + 
  ylab("% NCE Contribution to TPE") +
  xlab("Predator Density") +
  annotate('text', x = 0.45, y = 0.37, label = 'a') +
  annotate('text', x = 0.9, y = 0.42, label = 'b') +
  scale_x_continuous(expand = c(0, 0) ) + 
  scale_y_continuous(expand = c(0, 0), limits = c(0, 1), breaks = c(0, 0.25, 0.50, 0.75, 1) ) +
  scale_fill_continuous( type = "viridis" ) +
  theme( panel.border = element_rect( color = "black", fill = NA, linewidth = 0.75 ), aspect.ratio = 1, legend.position = "bottom")

preddens_4.plot <- ggplot( data = preddens_pctNCE.df, aes( x = k ) ) +
  geom_point( aes( y = OptimalRITR, fill = Fitness ), shape = 21, size = 2.5 ) +
  theme_classic( base_size = 10, base_line_size = 1 ) + 
  ylab("Optimal RITR") +
  xlab("Predator Density") +
  annotate('text', x = 0.45, y = 0.5, label = 'a') +
  annotate('text', x = 0.9, y = 0.35, label = 'b') +
  scale_x_continuous(expand = c(0, 0) ) + 
  scale_y_continuous(expand = c(0, 0), limits = c(0, 1), breaks = c(0, 0.50, 1), labels = c(0, 500, 1000) ) +
  scale_fill_continuous( type = "viridis" ) +
  theme( panel.border = element_rect( color = "black", fill = NA, linewidth = 0.75 ), aspect.ratio = 1,
         axis.title.x = element_blank(),
         axis.text.x = element_blank(), legend.position = "bottom" ) +
  guides(fill = "none")

preddens.fig <- plot_grid( preddens_1.plot, preddens_4.plot, preddens_2.plot, preddens_3.plot, ncol = 2, labels = c("a", "c", "b", "d"), hjust = -1.5, align = c("hv") )

# ggsave("fig2.png", plot = preddens.fig, dpi = 300)
```



```{r Figure 3: Displacement Rate - Predator Hunting Mode}
predmode.df <- read.csv("1-3-1_displacement_predmode.csv")
predmode_pctNCE.df <- read.csv("1-3-2_predmode_TPE_Opt.csv")

predmode_1.plot <- ggplot( data = predmode.df, aes( x = trait ) ) +
  geom_line( aes( y = growth_curve, color = "Growth" ) ) +
  geom_line( aes( y = mort_baseline, color = "Mortality" ), linetype = "dashed" ) +
  annotate(geom = "rect", xmin = preddens_optim - 0.025, xmax = preddens_optim + 0.025, 
           ymin = 1 - preddens_optim_NCE, ymax = 0.998, 
           color = "gray2", fill = "lightblue", alpha = 0.5) +
  annotate( "text", x = preddens_optim + 0.05, y = 1 - preddens_optim_NCE/2, 
            label = "NCE = 0.20", hjust = "left", size = 7/.pt  ) +
  annotate(geom = "rect", xmin = preddens_optim - 0.025, xmax = preddens_optim + 0.025,
           ymin = preddens_optim_CE, ymax = preddens_optim_CE + preddens_optim_fitness, 
           color = "gray2", fill = "lightgreen", alpha = 0.5) +
  annotate( "text", x = preddens_optim + 0.1, y = preddens_optim_CE + preddens_optim_fitness/2 - 0.05, 
            label = "0.48", hjust = "left", size = 7/.pt  ) +
  annotate(geom = "rect", xmin = preddens_optim - 0.025, xmax = preddens_optim + 0.025, 
           ymin = 0.001, ymax = preddens_optim_CE, 
           color = "gray2", fill = "red", alpha = 0.5) +
  annotate( "text", x = preddens_optim + 0.05, y = preddens_optim_CE/2, 
            label = "CE = 0.32", hjust = "left", size = 7/.pt  ) +
  annotate("text", x = 0.1, y = 0.05, label = "v = 0.2", size = 9/.pt ) +
  theme_classic( base_size = 10, base_line_size = 1 ) + 
  ylab("Growth and Mortality") +
  xlab("Displacement Rate") +
  scale_x_continuous(expand = c(0, 0), breaks = c(0, 0.5, 1), labels = c(1000, 500, 1) ) + 
  scale_y_continuous(expand = c(0, 0), limits = c(0, 1), breaks = c(0, 0.5, 1) ) +
  scale_color_manual(name = "Curve", values = c( "blue", "red" )) + 
  theme( panel.border = element_rect( color = "black", fill = NA, linewidth = 0.75 ), aspect.ratio = 1,
         axis.title.x = element_blank(),
         axis.text.x = element_blank(), legend.position = "bottom" ) + 
  guides(color = "none")

predmode_2.plot <- ggplot( data = predmode.df, aes( x = trait ) ) +
  geom_line( aes( y = growth_curve, colour = "Growth" ), ) +
  geom_line( aes( y = mort_curve, colour = "Mortality" ), linetype = "dashed" ) +
  theme_classic( base_size = 10, base_line_size = 1 ) + 
  ylab("Growth and Mortality") +
  xlab("Displacement Rate") +
  annotate(geom = "rect", xmin = predmode_optim - 0.025, xmax = predmode_optim + 0.025, 
           ymin = 1 - predmode_optim_NCE, ymax = 0.998, 
           color = "gray2", fill = "lightblue", alpha = 0.5) +
  annotate( "text", x = predmode_optim + 0.05, y = 1 - predmode_optim_NCE/2, 
            label = "NCE = 0.08", hjust = "left", size = 7/.pt  ) +
  annotate(geom = "rect", xmin = predmode_optim - 0.025, xmax = predmode_optim + 0.025,
           ymin = predmode_optim_CE, ymax = predmode_optim_CE + predmode_optim_fitness, 
           color = "gray2", fill = "lightgreen", alpha = 0.5) +
  annotate( "text", x = predmode_optim + 0.1, y = predmode_optim_CE + predmode_optim_fitness/2 - 0.05, 
            label = "0.19", hjust = "left", size = 7/.pt  ) +
  annotate(geom = "rect", xmin = predmode_optim - 0.025, xmax = predmode_optim + 0.025, 
           ymin = 0.001, ymax = predmode_optim_CE, 
           color = "gray2", fill = "red", alpha = 0.5) +
  annotate( "text", x = predmode_optim + 0.05, y = predmode_optim_CE/2, 
            label = "CE = 0.73", hjust = "left", size = 7/.pt  ) +
  annotate("text", x = 0.1, y = 0.05, label = "v = 1.0", size = 9/.pt ) +
  scale_x_continuous(expand = c(0, 0), breaks = c(0, 0.5, 1), labels = c(1000, 500, 1) ) + 
  scale_y_continuous(expand = c(0, 0), limits = c(0, 1), breaks = c(0, 0.5, 1) ) +
  scale_colour_manual(name = "Curve", values = c("blue", "red")) +
  theme( panel.border = element_rect( color = "black", fill = NA, linewidth = 0.75 ), aspect.ratio = 1 ) +
  theme( legend.position = "bottom" )

predmode_3.plot <- ggplot( data = predmode_pctNCE.df, aes( x = v ) ) +
  geom_point( aes( y = NCE_TPE, fill = Fitness ), shape = 21, color = "black", size = 2.5) +
  theme_classic( base_size = 10, base_line_size = 1 ) + 
  ylab("% NCE Contribution to TPE") +
  xlab("Predator Velocity") +
  annotate('text', x = 0.2, y = 0.5, label = 'a') +
  annotate('text', x = 1, y = 0.17, label = 'b') +
  scale_x_continuous(expand = c(0, 0) ) + 
  scale_y_continuous(expand = c(0, 0), limits = c(0, 1), breaks = c(0, 0.25, 0.50, 0.75, 1) ) +
  scale_fill_continuous( type = "viridis" ) +
  theme( panel.border = element_rect( color = "black", fill = NA, linewidth = 0.75 ), aspect.ratio = 1, legend.position = "bottom")

predmode_4.plot <- ggplot( data = predmode_pctNCE.df, aes( x = v ) ) +
  geom_point( aes( y = OptimalRITR, fill = Fitness ), shape = 21, color = "black", size = 2.5 ) +
  theme_classic( base_size = 10, base_line_size = 1 ) + 
  ylab("Optimal RITR") +
  xlab("Predator Velocity") +
  annotate('text', x = 0.2, y = 0.45, label = 'a') +
  annotate('text', x = 1, y = 0.62, label = 'b') +
  scale_x_continuous(expand = c(0, 0) ) + 
  scale_y_continuous(expand = c(0, 0), limits = c(0, 1), breaks = c(0, 0.50, 1), labels = c(0, 500, 1000) ) +
  scale_fill_continuous( type = "viridis" ) +
  theme( panel.border = element_rect( color = "black", fill = NA, linewidth = 0.75 ), 
         axis.title.x = element_blank(),
         axis.text.x = element_blank(),
         aspect.ratio = 1, 
         legend.position = "bottom" ) +
  guides( fill = "none" )

predmode.fig <- plot_grid( predmode_1.plot, predmode_4.plot, predmode_2.plot, predmode_3.plot, ncol = 2, labels = c("a", "c", "b", "d"), hjust = -1.5, align = c("hv") )

# ggsave("fig3.png", plot = predmode.fig, dpi = 300)
```



```{r Figure 4: Refuge Use - Increasing Resource Processing Rate}
refuge.df <- read.csv("2-1_refuge_res_base.csv")
refuge2.df <- read.csv("2-2_refuge_res_fast_h.csv")
prey_h_pctNCE.df <- read.csv("2-3_refuge_res_TPE_Opt.csv")
refuge_summary.df <- read.csv("2-4_refuge_res_summary.csv") # See above

refuge_1.plot <- ggplot( data = refuge.df, aes( x = proptime ) ) +
  geom_line( aes( y = mort_curve, color = "Mortality" ), linetype = "dashed" ) +
  geom_line( aes( y = growth_curve, color = "Growth" ) ) +
  theme_classic( base_size = 10, base_line_size = 1 ) + 
  annotate(geom = "rect", xmin = refuge_optim - 0.025, xmax = refuge_optim + 0.025, 
           ymin = 1 - refuge_optim_NCE, ymax = 0.998, 
           color = "gray2", fill = "lightblue", alpha = 0.5) +
  annotate( "text", x = refuge_optim - 0.25, y = 1 - refuge_optim_NCE/2 + 0.035, 
            label = "NCE = 0.11", hjust = "left", size = 7/.pt  ) +
  annotate(geom = "rect", xmin = refuge_optim - 0.025, xmax = refuge_optim + 0.025,
           ymin = refuge_optim_CE, ymax = refuge_optim_CE + refuge_optim_fitness, 
           color = "gray2", fill = "lightgreen", alpha = 0.5) +
  annotate( "text", x = refuge_optim - 0.2, y = refuge_optim_CE + refuge_optim_fitness/2, 
            label = "0.72", hjust = "left", size = 7/.pt  ) +
  annotate(geom = "rect", xmin = refuge_optim - 0.025, xmax = refuge_optim + 0.025, 
           ymin = 0.001, ymax = refuge_optim_CE, 
           color = "gray2", fill = "red", alpha = 0.5) +
  annotate( "text", x = refuge_optim - 0.25, y = refuge_optim_CE/2, 
            label = "CE = 0.17", hjust = "left", size = 7/.pt  ) +
  annotate("text", x = 0.85, y = 0.95, label = "1/h = 0.1", size = 9/.pt ) +
  ylab("Growth and Mortality") +
  xlab("Proportion of Time Spent in Refuge") +
  scale_x_continuous(expand = c(0, 0), breaks = c(0, 0.5, 1), labels = c(0, 0.5, 1) ) + 
  scale_y_continuous(expand = c(0, 0), limits = c(0, 1), breaks = c(0, 0.5, 1) ) +
  scale_color_manual(name = "Curve", values = c( "blue", "red" )) + 
  theme( panel.border = element_rect( color = "black", fill = NA, linewidth = 0.75 ), aspect.ratio = 1,
         axis.title.x = element_blank(),
         axis.text.x = element_blank(), legend.position = "bottom" ) + 
  guides(color = "none")


refuge_2.plot <- ggplot( data = refuge2.df, aes( x = proptime ) ) +
  geom_line( aes( y = growth_curve, color = "Growth" ) ) +
  geom_line( aes( y = mort_curve, color = "Mortality" ), linetype = "dashed" ) +
  annotate(geom = "rect", xmin = refuge_optim2 - 0.025, xmax = refuge_optim2 + 0.025, 
           ymin = 1 - refuge_optim_NCE2, ymax = 0.998, 
           color = "gray2", fill = "lightblue", alpha = 0.5) +
  annotate( "text", x = refuge_optim2 + 0.05, y = 1 - refuge_optim_NCE2/2, 
            label = "NCE = 0.05", hjust = "left", size = 7/.pt  ) +
  annotate(geom = "rect", xmin = refuge_optim2 - 0.025, xmax = refuge_optim2 + 0.025,
           ymin = refuge_optim_CE2, ymax = refuge_optim_CE2 + refuge_optim_fitness2, 
           color = "gray2", fill = "lightgreen", alpha = 0.5) +
  annotate( "text", x = refuge_optim2 + 0.1, y = refuge_optim_CE2 + refuge_optim_fitness2/2, 
            label = "0.60", hjust = "left", size = 7/.pt  ) +
  annotate(geom = "rect", xmin = refuge_optim2 - 0.025, xmax = refuge_optim2 + 0.025, 
           ymin = 0.001, ymax = refuge_optim_CE2, 
           color = "gray2", fill = "red", alpha = 0.5) +
  annotate( "text", x = refuge_optim2 + 0.05, y = refuge_optim_CE2/2, 
            label = "CE = 0.35", hjust = "left", size = 7/.pt  ) +
  annotate("text", x = 0.85, y = 0.95, label = "1/h = 0.5", size = 9/.pt ) +
  theme_classic( base_size = 10, base_line_size = 1 ) + 
  ylab("Growth and Mortality") +
  xlab("Proportion of Time Spent in Refuge") +
  scale_x_continuous(expand = c(0, 0), breaks = c(0, 0.5, 1), labels = c(0, 0.5, 1) ) + 
  scale_y_continuous(expand = c(0, 0), limits = c(0, 1), breaks = c(0, 0.5, 1) ) +
  scale_color_manual(name = "Curve", values = c( "blue", "red" )) + 
  theme( panel.border = element_rect( color = "black", fill = NA, linewidth = 0.75 ), aspect.ratio = 1 ) +
  theme( legend.position = "bottom" )

refuge_3.plot <- ggplot( data = prey_h_pctNCE.df, aes( x = intake ) ) +
  geom_point( aes( y = NCE_TPE, fill = Fitness ), shape = 21, size = 2.5, color = "black" ) +
  theme_classic( base_size = 10, base_line_size = 1 ) + 
  ylab("% NCE Contribution to TPE") +
  xlab("Prey Resource Processing Rate (1/h)") +
  annotate('text', x = 0.1, y = 0.475, label = 'a') +
  annotate('text', x = 0.5, y = 0.2, label = 'b') +
  scale_x_continuous(expand = c(0, 0) ) + 
  scale_y_continuous(expand = c(0, 0), limits = c(0, 1), breaks = c(0, 0.25, 0.50, 0.75, 1) ) +
  scale_fill_continuous(type = "viridis" ) +
  theme( panel.border = element_rect( color = "black", fill = NA, linewidth = 0.75 ), aspect.ratio = 1, 
         legend.position = "bottom" )

refuge_4.plot <- ggplot( data = prey_h_pctNCE.df, aes( x = intake ) ) +
  geom_point( aes( y = OptimalRITR, fill = Fitness ), shape = 21, size = 2.5, color = "black" ) +
  theme_classic( base_size = 10, base_line_size = 1 ) + 
  ylab("Optimal RITR") +
  xlab("Prey Resource Processing Rate (1/h)") +
  annotate('text', x = 0.1, y = 0.675, label = 'a') +
  annotate('text', x = 0.5, y = 0.19, label = 'b') +
  scale_x_continuous(expand = c(0, 0) ) + 
  scale_y_continuous(expand = c(0, 0), limits = c(0, 1), breaks = c(0, 0.25, 0.5, 0.75, 1) ) +
  scale_fill_continuous(type = "viridis") +
  theme( panel.border = element_rect( color = "black", fill = NA, linewidth = 0.75 ), axis.title.x = element_blank(),
         axis.text.x = element_blank(), aspect.ratio = 1, legend.position = "bottom" ) +
  guides(fill = "none" )

predmode.fig <- plot_grid( refuge_1.plot, refuge_4.plot, refuge_2.plot, refuge_3.plot, ncol = 2, labels = c("a", "c", "b", "d"), hjust = -1.5, align = c("hv") )

# ggsave("fig4.png", plot = predmode.fig, dpi = 300)
```



```{r}
therm_refuge.df <- read.csv("3-1_refuge_therm_base.csv")
therm_refuge2.df <- read.csv("3-2_refuge_therm_warmed.csv")
therm_refuge_summary.df <- read.csv("3-3_refuge_therm_summary.csv") # See above


## The growth-trait curve
# a.growth determines the width of the performance curve and should be negative, so that the curve is concave down
# h.growth determines the temperature at which prey growth peaks
# c.growth is a scaling constant
# temp_C is temperature in degrees Celsius
growth.curve_warming <- function( c_g, a_g, h_g, temp_C ){
  c_g * exp( a_g * ( ( temp_C - h_g )^2 ) + 1)
}

a_g.val <- -0.05 # Set a.growth to an arbitrary value that makes the curve broader than the predator's distribution; smaller values yield broader curves
h_g.val <- 20 # Set h.growth to the same point that the predator's density peaks
c_g.val <- 1/exp(1) # c.growth needs to be 1/e for this parameterization to peak at 1

#Make a plot of the initial TPC
temp_vec <- seq( 10, 26, by = 0.1 )
tpc.df <- as.data.frame( mat.or.vec (length(temp_vec), 2) )
colnames(tpc.df) <- c("temperature", "performance")
tpc.df$temperature <- temp_vec
tpc.df$performance <- growth.curve_warming( c_g = c_g.val, a_g = a_g.val, h_g = h_g.val, temp_C = temp_vec)

tpc_labels.df <- as.data.frame( mat.or.vec ( 2, 2 ) )
colnames(tpc_labels.df) <- c("temperature", "performance")
tpc_labels.df$temperature <- c(19, 22)
tpc_labels.df$performance <- c( 0.951229425, 0.818730753)

tpc_1.plot <- ggplot(data = tpc.df, aes( x = temperature, y = performance ) ) +
  geom_line() + 
  geom_point( data = tpc_labels.df ) +
  geom_text( data = tpc_labels.df, label = c("A", "B"), nudge_x = 1 ) + 
  theme_classic( base_size = 10, base_line_size = 1 ) + 
  ylab("Prey Growth") +
  xlab("Temperature (°C)") +
  scale_x_continuous(expand = c(0, 0), breaks = c(10, 17.5, 25), labels = c("Cool", "Warm", "Hot") ) + 
  scale_y_continuous(expand = c(0, 0), limits = c(0, 1.1), breaks = c(0, 0.5, 1) ) +
  theme( panel.border = element_rect( color = "black", fill = NA, linewidth = 0.75 ), aspect.ratio = 1,
         axis.title.x = element_blank(),
         axis.text.x = element_blank() ) 

# Plot of Unwarmed Scenario
therm_refuge_1.plot <- ggplot( data = therm_refuge.df, aes( x = proptime ) ) +
  geom_line( aes( y = growth_curve, color = "Growth" ) ) +
  geom_line( aes( y = mort_curve, color = "red" ), linetype = "dashed" ) +
  annotate(geom = "rect", xmin = therm_refuge_optim - 0.05, xmax = therm_refuge_optim, 
           ymin = 1 - therm_refuge_optim_NCE, ymax = 0.998, 
           color = "gray2", fill = "lightblue", alpha = 0.5) +
  annotate( "text", x = therm_refuge_optim - 0.35, y = 0.975, 
            label = "NCE = 0.18", hjust = "left", size = 8/.pt  ) +
  annotate(geom = "rect", xmin = therm_refuge_optim - 0.05, xmax = therm_refuge_optim,
           ymin = therm_refuge_optim_CE, ymax = therm_refuge_optim_CE + therm_refuge_optim_fitness, 
           color = "gray2", fill = "lightgreen", alpha = 0.5) +
  annotate( "text", x = therm_refuge_optim - 0.3, y = therm_refuge_optim_CE + therm_refuge_optim_fitness/2, 
            label = "0.82", hjust = "left", size = 8/.pt  ) +
  annotate(geom = "rect", xmin = therm_refuge_optim - 0.05, xmax = therm_refuge_optim, 
           ymin = 0.001, ymax = therm_refuge_optim_CE, 
           color = "gray2", fill = "red", alpha = 0.5) +
  annotate( "text", x = therm_refuge_optim - 0.35, y = 0.05, 
            label = "CE = 0", hjust = "left", size = 8/.pt  ) +
  theme_classic( base_size = 10, base_line_size = 1 ) + 
  ylab("Growth and Mortality") +
  xlab("Proportion of Time Spent in Refuge") +
  scale_x_continuous(expand = c(0, 0), breaks = c(0, 0.5, 1), labels = c(1000, 500, 1) ) + 
  scale_y_continuous(expand = c(0, 0), limits = c(0, 1), breaks = c(0, 0.5, 1) ) +
  scale_color_manual(name = "Curve", values = c( "blue", "red" )) + 
  theme( panel.border = element_rect( color = "black", fill = NA, linewidth = 0.75 ), aspect.ratio = 1,
         axis.title.x = element_blank(),
         axis.text.x = element_blank(), legend.position = "bottom" ) + 
  theme(legend.key = element_rect(fill = "white"), legend.text = element_text(color = "white"), legend.title = element_text(color = "white")) +
  guides(color = guide_legend(override.aes = list(color = NA)))


# Repeat TPC plot with new temperatures
tpc_labels2.df <- as.data.frame( mat.or.vec ( 2, 2 ) )
colnames(tpc_labels2.df) <- c("temperature", "performance")
tpc_labels2.df$temperature <- c(21.5, 24.5)
tpc_labels2.df$performance <- c( 0.893597347, 0.363309569)

tpc_2.plot <- ggplot(data = tpc.df, aes( x = temperature, y = performance ) ) +
  geom_line() + 
  geom_point( data = tpc_labels2.df ) +
  geom_text( data = tpc_labels2.df, label = c("A", "B"), nudge_x = -1 ) + 
  annotate("segment", x = 17.5, y = 0.25, xend = 23, yend = 0.25,
    arrow = arrow(),
    color = "red",
    size = 1) +
  annotate( "text", x = 20, y = 0.4, color = "red", label = "Warming") +
  theme_classic( base_size = 10, base_line_size = 1 ) + 
  ylab("Prey Growth") +
  xlab("Temperature (°C)") +
  scale_x_continuous(expand = c(0, 0), breaks = c(10, 17.5, 25), labels = c("Cool", "Warm", "Hot") ) + 
  scale_y_continuous(expand = c(0, 0), limits = c(0, 1.1), breaks = c(0, 0.5, 1) ) +
  theme( panel.border = element_rect( color = "black", fill = NA, linewidth = 0.75 ), aspect.ratio = 1 )


therm_refuge_2.plot <- ggplot( data = therm_refuge2.df, aes( x = proptime ) ) +
  geom_line( aes( y = growth_curve, color = "Growth" ) ) +
  geom_line( aes( y = mort_curve, color = "Mortality" ), linetype = "dashed" ) +
  annotate(geom = "rect", xmin = therm_refuge_optim2, xmax = therm_refuge_optim2 + 0.05, 
           ymin = 1 - therm_refuge_optim_NCE2, ymax = 0.998, 
           color = "gray2", fill = "lightblue", alpha = 0.5) +
  annotate( "text", x = therm_refuge_optim2 + 0.1, y = 0.975, 
            label = "NCE = 0", hjust = "left", size = 8/.pt  ) +
  annotate(geom = "rect", xmin = therm_refuge_optim2, xmax = therm_refuge_optim2 + 0.05,
           ymin = therm_refuge_optim_CE2, ymax = therm_refuge_optim_CE2 + therm_refuge_optim_fitness2, 
           color = "gray2", fill = "lightgreen", alpha = 0.5) +
  annotate( "text", x = therm_refuge_optim2 + 0.15, y = therm_refuge_optim_CE2 + therm_refuge_optim_fitness2/2, 
            label = "0.6", hjust = "left", size = 8/.pt  ) +
  annotate(geom = "rect", xmin = therm_refuge_optim2, xmax = therm_refuge_optim2 + 0.05, 
           ymin = 0.001, ymax = therm_refuge_optim_CE2, 
           color = "gray2", fill = "red", alpha = 0.5) +
  annotate( "text", x = therm_refuge_optim2 + 0.1, y = therm_refuge_optim_CE2/2, 
            label = "CE = 0.4", hjust = "left", size = 8/.pt  ) +
  theme_classic( base_size = 10, base_line_size = 1 ) + 
  ylab("Growth and Mortality") +
  xlab("Proportion of Time Spent in Refuge") +
  scale_x_continuous(expand = c(0, 0), breaks = c(0, 0.5, 1), labels = c(0, 0.5, 1) ) + 
  scale_y_continuous(expand = c(0, 0), limits = c(0, 1), breaks = c(0, 0.5, 1) ) +
  scale_color_manual(name = "Curve", values = c( "blue", "red" )) + 
  theme( panel.border = element_rect( color = "black", fill = NA, linewidth = 0.75 ), aspect.ratio = 1) +
  theme( legend.position = "bottom" )

warming.fig <- plot_grid( tpc_1.plot, therm_refuge_1.plot, tpc_2.plot, therm_refuge_2.plot, ncol = 2, labels = c("a", "c", "b", "d"), hjust = -1.5, align = c("hv") )


# ggsave("fig5.png", plot = warming.fig, dpi = 300)
```

```{r}
# Figs above but mu/g
fig1s_a.plot <- ggplot( data = baseline.df, aes( x = trait ) ) +
  geom_line( aes( y = growth_curve, color = "Growth" ) ) +
  geom_line( aes( y = mort_curve, color = "Mortality" ), linetype = "dashed" ) +
  geom_line( aes( y = mu_g, color = "mu_g" ) ) +
  geom_vline( xintercept = baseline_optim_mu_g, linetype = "dashed", color = "green" ) +
  theme_classic( base_size = 10, base_line_size = 1 ) + 
  ylab("Growth and Mortality") +
  xlab("") +
  scale_x_continuous(expand = c(0, 0), breaks = c(0, 0.5, 1), labels = c(1000, 500, 1) ) + 
  scale_y_continuous(expand = c(0, 0), limits = c(0, 1), breaks = c(0, 0.5, 1) ) +
  scale_color_manual(name = "Curve", values = c( "blue", "red", "green" )) + 
  theme( panel.border = element_rect( color = "black", fill = NA, linewidth = 0.75 ), aspect.ratio = 1,
         axis.title.x = element_blank(),
         axis.text.x = element_blank(), legend.position = "bottom" ) + 
  theme(legend.key = element_rect(fill = "white"), legend.text = element_text(color = "white"), legend.title = element_text(color = "white")) +
  guides(color = guide_legend(override.aes = list(color = NA)))

fig1s_b.plot <- ggplot( data = preddens.df, aes( x = trait ) ) +
  geom_line( aes( y = growth_curve, color = "Growth" ) ) +
  geom_line( aes( y = mort_curve, color = "Mortality" ), linetype = "dashed" ) +
  geom_line( aes( y = mu_g, color = "mu_g" ) ) +
  geom_vline( xintercept = preddens_optim_mu_g, linetype = "dashed", color = "green" ) +
  theme_classic( base_size = 10, base_line_size = 1 ) + 
  ylab("Growth and Mortality") +
  xlab("") +
  annotate("text", x = 0.85, y = 0.95, label = "P = 0.9", size = 7/.pt ) +
  scale_x_continuous(expand = c(0, 0), breaks = c(0, 0.5, 1), labels = c(1000, 500, 1) ) + 
  scale_y_continuous(expand = c(0, 0), limits = c(0, 1), breaks = c(0, 0.5, 1) ) +
  scale_color_manual(name = "Curve", values = c( "blue", "red", "green" )) + 
  theme( panel.border = element_rect( color = "black", fill = NA, linewidth = 0.75 ), aspect.ratio = 1,
         axis.title.x = element_blank(),
         axis.text.x = element_blank(), legend.position = "bottom" ) + 
  theme(legend.key = element_rect(fill = "white"), legend.text = element_text(color = "white"), legend.title = element_text(color = "white")) +
  guides(color = guide_legend(override.aes = list(color = NA)))

fig1s_c.plot <- ggplot( data = predmode.df, aes( x = trait ) ) +
  geom_line( aes( y = growth_curve, color = "Growth" ) ) +
  geom_line( aes( y = mort_curve, color = "Mortality" ), linetype = "dashed" ) +
  geom_line( aes( y = mu_g, color = "mu_g" ) ) +
  geom_vline( xintercept = predmode_optim_mu_g, linetype = "dashed", color = "green" ) +
  theme_classic( base_size = 10, base_line_size = 1 ) + 
  ylab("Growth and Mortality") +
  xlab("Displacement Rate") +  
  annotate("text", x = 0.85, y = 0.95, label = "v = 1", size = 7/.pt ) +
  scale_x_continuous(expand = c(0, 0), breaks = c(0, 0.5, 1), labels = c(1000, 500, 1) ) + 
  scale_y_continuous(expand = c(0, 0), limits = c(0, 1), breaks = c(0, 0.5, 1) ) +
  scale_color_manual(name = "Curve", values = c( "blue", "red", "green" )) + 
  theme( panel.border = element_rect( color = "black", fill = NA, linewidth = 0.75 ), aspect.ratio = 1, legend.position = "bottom" )

s1_fig <- plot_grid( fig1s_a.plot, fig1s_b.plot, fig1s_c.plot, ncol = 1, labels = "auto", label_x = 0.25, align = c("hv") )

# ggsave("figS1.png", plot = s1_fig, dpi = 300)
```

```{r}
# mu_g plots for habitat selection

fig2s_a.plot <- ggplot( data = refuge.df, aes( x = proptime ) ) +
  geom_line( aes( y = mort_curve, color = "Mortality" ), linetype = "dashed" ) +
  geom_line( aes( y = growth_curve, color = "Growth" ) ) +
  geom_line( aes( y = mu_g, color = "mu_g" ) ) +
  theme_classic( base_size = 10, base_line_size = 1 ) + 
  annotate("text", x = 0.85, y = 0.95, label = "1/h = 0.1", size = 9/.pt ) +
  ylab("Growth and Mortality") +
  xlab("Prop. Time Spent in Refuge") +
  scale_x_continuous(expand = c(0, 0), breaks = c(0, 0.5, 1), labels = c(0, 0.5, 1) ) + 
  scale_y_continuous(expand = c(0, 0), limits = c(0, 1), breaks = c(0, 0.5, 1) ) +
  scale_color_manual(name = "Curve", values = c( "blue", "red", "green" )) + 
  theme( panel.border = element_rect( color = "black", fill = NA, linewidth = 0.75 ), aspect.ratio = 1,
         axis.title.x = element_blank(),
         axis.text.x = element_blank(), legend.position = "bottom" ) + 
  theme(legend.key = element_rect(fill = "white"), legend.text = element_text(color = "white"), legend.title = element_text(color = "white")) +
  guides(color = guide_legend(override.aes = list(color = NA)))


fig2s_b.plot <- ggplot( data = refuge2.df, aes( x = proptime ) ) +
  geom_line( aes( y = growth_curve, color = "Growth" ) ) +
  geom_line( aes( y = mort_curve, color = "Mortality" ), linetype = "dashed" ) +
  geom_line( aes( y = mu_g, color = "mu_g" ) ) +
  annotate("text", x = 0.85, y = 0.95, label = "1/h = 0.5", size = 9/.pt ) +
  theme_classic( base_size = 10, base_line_size = 1 ) + 
  ylab("") +
  xlab("Prop. Time Spent in Refuge") +
  scale_x_continuous(expand = c(0, 0), breaks = c(0, 0.5, 1), labels = c(0, 0.5, 1) ) + 
  scale_y_continuous(expand = c(0, 0), limits = c(0, 1), breaks = c(0, 0.5, 1) ) +
  scale_color_manual(name = "Curve", values = c( "blue", "red", "green" )) + 
  theme( panel.border = element_rect( color = "black", fill = NA, linewidth = 0.75 ), aspect.ratio = 1 ) +
  theme( legend.position = "bottom" )

s2_fig <- plot_grid( fig2s_a.plot, fig2s_b.plot, ncol = 1, labels = "auto", label_x = 0.25, align = c("hv") )

# ggsave("figS2.png", plot = s2_fig, dpi = 300)


# Plot of Unwarmed Scenario
fig3s_a.plot <- ggplot( data = therm_refuge.df, aes( x = proptime ) ) +
  geom_line( aes( y = growth_curve, color = "Growth" ) ) +
  geom_line( aes( y = mort_curve, color = "Mortality" ), linetype = "dashed" ) +
  geom_line( aes( y = mu_g, color = "mu_g" ) ) +
  theme_classic( base_size = 10, base_line_size = 1 ) + 
  annotate("text", x = 0.85, y = 0.95, label = "T1", size = 9/.pt ) +
  ylab("Growth and Mortality") +
  xlab("Prop. Time Spent in Refuge") +
  scale_x_continuous(expand = c(0, 0), breaks = c(0, 0.5, 1), labels = c(0, 0.5, 1) ) + 
  scale_y_continuous(expand = c(0, 0), limits = c(0, 1), breaks = c(0, 0.5, 1) ) +
  scale_color_manual(name = "Curve", values = c( "blue", "red", "green" )) + 
  theme( panel.border = element_rect( color = "black", fill = NA, linewidth = 0.75 ), aspect.ratio = 1,
         axis.title.x = element_blank(),
         axis.text.x = element_blank(), legend.position = "bottom" ) + 
  theme(legend.key = element_rect(fill = "white"), legend.text = element_text(color = "white"), legend.title = element_text(color = "white")) +
  guides(color = guide_legend(override.aes = list(color = NA)))


fig3s_b.plot <- ggplot( data = therm_refuge2.df, aes( x = proptime ) ) +
  geom_line( aes( y = growth_curve, color = "Growth" ) ) +
  geom_line( aes( y = mort_curve, color = "Mortality" ), linetype = "dashed" ) +
  geom_line( aes( y = mu_g, color = "mu_g" ) ) +
  annotate("text", x = 0.85, y = 0.95, label = "T2", size = 9/.pt ) +
  theme_classic( base_size = 10, base_line_size = 1 ) + 
  ylab("Growth and Mortality") +
  xlab("Prop. Time Spent in Refuge") +
  scale_x_continuous(expand = c(0, 0), breaks = c(0, 0.5, 1), labels = c(0, 0.5, 1) ) + 
  scale_y_continuous(expand = c(0, 0), limits = c(0, 1), breaks = c(0, 0.5, 1) ) +
  scale_color_manual(name = "Curve", values = c( "blue", "red", "green" )) + 
  theme( panel.border = element_rect( color = "black", fill = NA, linewidth = 0.75 ), aspect.ratio = 1) +
  theme( legend.position = "bottom" )

s3_fig <- plot_grid( fig3s_a.plot, fig3s_b.plot, ncol = 1, labels = "auto", label_x = 0.25, align = c("hv") )

# ggsave("figS3.png", plot = s3_fig, dpi = 300)
```